spring.application.name=sample_ai
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=qwen2.5:7b 
spring.ai.ollama.chat.options.temperature=0.0
spring.ai.ollama.embedding.model=nomic-embed-text

spring.ai.vectorstore.chroma.client.host=http://localhost
spring.ai.vectorstore.chroma.client.port=8000
spring.ai.vectorstore.chroma.collection-name=sample_ai_code


spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=qwen-assistente-group